export type itemWalletType =
   "Carteira de identidade (RG)"
  | "Cadastro de Pessoas Físicas (Cpf)"
  | "Carteira de Habilitação nacional (CNH)"
  | "Título de Eleitor"
  | "Passaporte"
  | "Certidão de Nascimento"
  | "Certidão de Casamento"
  | "Certidão de Óbito"
  | "Certidão de Divórcio"
  | "Carteira de Trabalho"
  | "Cartão do SUS (CNS)"
  | "Certificado de alistamento militar (CAM)"
  | "Certificado de reservista"
  | "Certificado de dispensa de incorporação (CDI)"
  | "Certificado de dispensa militar (CDM)"
  | "Certificado de isenção de serviço militar (CISM)"
  | "Cartão de Vacinação"
  | "Cartão de Crédito"
  | "Cartão de Débito"
  | "Cartão de Loja"
  | "Cartão de Transporte"
  | "Cartão de Benefício"
  | "Cartão de Plano de Saúde"
  | "Carteirinha do Estudante"
  | "Carteirinha de Associado";